version: '3'
services:

  gbs-db:
    image: postgres:14.5
    container_name: gbs-db
    volumes:
      - ./data/data-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gbs
      POSTGRES_PASSWORD: Amk2010
      POSTGRES_USER: mikita
    networks:
      - gamesbox

  gamesbox-mono:
    container_name: gamesbox-mono
    build: ./
    depends_on:
      - gbs-db
    ports:
      - 8080:8080
    networks:
      - gamesbox

networks:
  gamesbox:
    driver: bridge
